[pyroll]

# list full qualified names of plugins to load (as they were importable in real python code)
plugins = [
    {% for p in plugins %}" {{- p -}} ",
    {% endfor %}
]

{% for m, cs in config_constants.items() %}
[{{- m -}}]
{% for c in cs %}
{{-c-}}
{% endfor -%}
{% endfor %}
[logging] # configuration for the logging standard library package
version = 1

formatters.console.format = '[%(levelname)s] %(name)s: %(message)s'
formatters.file.format = '%(asctime)s [%(levelname)s] %(name)s: %(message)s'

[logging.handlers.console]

class = "logging.StreamHandler"
level = "INFO"
formatter = "console"
stream = "ext://sys.stdout"

[logging.handlers.file]
class = "logging.FileHandler"
level = "DEBUG"
formatter = "file"
filename = "pyroll.log"

[logging.root]
level = "WARNING"
handlers = ["console", "file"]

[logging.loggers.pyroll]
level = "DEBUG"
