[pyroll]
plugins = [# list of plugin packages to load
    {% for p in plugins %}" {{- p -}} ",
    {% endfor %}
]

# configuration constants for core and plugin packages
{% for m, cs in config_constants.items() %}
[{{- m -}}]
{% for c in cs %}
{{-c-}}
{% endfor -%}
{% endfor %}

[logging] # configuration for the logging standard library package
version = 1

formatters.console.format = '[bold]%(name)s:[/bold] %(message)s'
formatters.file.format = '%(asctime)s [%(levelname)s] %(name)s: %(message)s'

[logging.handlers.console]
class = "rich.logging.RichHandler"
level = "INFO"
formatter = "console"
markup = true
rich_tracebacks = true
tracebacks_suppress = [
    "pyroll.core.hooks",
]

[logging.handlers.file]
class = "logging.FileHandler"
level = "DEBUG"
formatter = "file"
filename = "pyroll.log"

[logging.root]
level = "WARNING"
handlers = ["console", "file"]

[logging.loggers.pyroll]
level = "DEBUG"
