[build]
packages = [
    "pyroll"
]

[version]
path = "pyroll/cli/__init__.py"

[envs.default]
path = ".venv"
dependencies = [
    "pytest ~= 7.0",
]

[envs.test]
path = ""
dependencies = [
    "pytest ~= 7.0",
]

[[envs.test.matrix]]
python = ["3.9", "3.10", "3.11"]

[envs.test.scripts]
all = "pytest tests"